# Generated by Django 4.2.7 on 2023-11-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.CharField(choices=[('map1', 'Map 1'), ('map2', 'Map 2')], max_length=100)),
                ('trainer_type', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2')], max_length=100)),
                ('trainer_name', models.CharField(max_length=100)),
                ('encounter_dialog', models.TextField()),
                ('lose_dialog', models.TextField()),
                ('pokemon1', models.CharField(choices=[('pokemon1', 'Pokemon 1'), ('pokemon2', 'Pokemon 2')], max_length=100)),
                ('pokemon2', models.CharField(choices=[('pokemon1', 'Pokemon 1'), ('pokemon2', 'Pokemon 2')], max_length=100)),
                ('pokemon3', models.CharField(choices=[('pokemon1', 'Pokemon 1'), ('pokemon2', 'Pokemon 2')], max_length=100)),
                ('pokemon4', models.CharField(choices=[('pokemon1', 'Pokemon 1'), ('pokemon2', 'Pokemon 2')], max_length=100)),
                ('pokemon5', models.CharField(choices=[('pokemon1', 'Pokemon 1'), ('pokemon2', 'Pokemon 2')], max_length=100)),
                ('pokemon6', models.CharField(choices=[('pokemon1', 'Pokemon 1'), ('pokemon2', 'Pokemon 2')], max_length=100)),
                ('pokemon_level', models.IntegerField()),
            ],
        ),
    ]
