# Generated by Django 4.2.7 on 2023-11-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounter_creation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
